version: '3'
services:
  app:
    container_name: ubuntu-node-mongo
    restart: always
    build: .
    ports:
      - '4800:4200'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

networks:
  app:
    external: true
